### ISSUE TITLE
Feature request: Chrome extension to display data on saltybet.com near betting buttons

### ISSUE THREAD

**Issue by calexil** [mrmoss/saltybet_tracker#2]
a simple chrome extension that scrapes the match percentage data and displays it near the betting buttons so users don't have to have another tab open would be awesome

**Comment by mrmoss** [comment]
[Check it out: https://github.com/mrmoss/saltybet_tools_chrome_extension](https://github.com/mrmoss/saltybet_tools_chrome_extension)

**Comment by calexil** [comment]
thats effing awesome, any way you can have it display the win percentage as well?
